"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _InputType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _InputTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_InputType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    STRING: _InputType.ValueType  # 0
    INT: _InputType.ValueType  # 1
    FLOAT: _InputType.ValueType  # 2
    BOOL: _InputType.ValueType  # 3

class InputType(_InputType, metaclass=_InputTypeEnumTypeWrapper): ...

STRING: InputType.ValueType  # 0
INT: InputType.ValueType  # 1
FLOAT: InputType.ValueType  # 2
BOOL: InputType.ValueType  # 3
global___InputType = InputType

@typing.final
class FunctionInput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    DEFAULT_FIELD_NUMBER: builtins.int
    INPUTHELP_FIELD_NUMBER: builtins.int
    Name: builtins.str
    Type: global___InputType.ValueType
    Default: builtins.str
    InputHelp: builtins.str
    def __init__(
        self,
        *,
        Name: builtins.str = ...,
        Type: global___InputType.ValueType = ...,
        Default: builtins.str = ...,
        InputHelp: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Default", b"Default", "InputHelp", b"InputHelp", "Name", b"Name", "Type", b"Type"]) -> None: ...

global___FunctionInput = FunctionInput

@typing.final
class PluginCommand(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COMMANDNAME_FIELD_NUMBER: builtins.int
    FUNCTIONINPUTDEFS_FIELD_NUMBER: builtins.int
    SUBCOMMANDS_FIELD_NUMBER: builtins.int
    COMMANDHELP_FIELD_NUMBER: builtins.int
    CommandName: builtins.str
    CommandHelp: builtins.str
    @property
    def FunctionInputDefs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FunctionInput]: ...
    @property
    def SubCommands(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PluginCommand]: ...
    def __init__(
        self,
        *,
        CommandName: builtins.str = ...,
        FunctionInputDefs: collections.abc.Iterable[global___FunctionInput] | None = ...,
        SubCommands: collections.abc.Iterable[global___PluginCommand] | None = ...,
        CommandHelp: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["CommandHelp", b"CommandHelp", "_CommandHelp", b"_CommandHelp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["CommandHelp", b"CommandHelp", "CommandName", b"CommandName", "FunctionInputDefs", b"FunctionInputDefs", "SubCommands", b"SubCommands", "_CommandHelp", b"_CommandHelp"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_CommandHelp", b"_CommandHelp"]) -> typing.Literal["CommandHelp"] | None: ...

global___PluginCommand = PluginCommand

@typing.final
class PluginDefintion(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PLUGINNAME_FIELD_NUMBER: builtins.int
    PLUGINUUID_FIELD_NUMBER: builtins.int
    PLUGINCOMMANDS_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    BINARYLOC_FIELD_NUMBER: builtins.int
    GITSHA_FIELD_NUMBER: builtins.int
    PluginName: builtins.str
    PluginUUID: builtins.int
    Address: builtins.str
    BinaryLoc: builtins.str
    GitSha: builtins.str
    @property
    def PluginCommands(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PluginCommand]: ...
    def __init__(
        self,
        *,
        PluginName: builtins.str = ...,
        PluginUUID: builtins.int = ...,
        PluginCommands: collections.abc.Iterable[global___PluginCommand] | None = ...,
        Address: builtins.str | None = ...,
        BinaryLoc: builtins.str | None = ...,
        GitSha: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["Address", b"Address", "BinaryLoc", b"BinaryLoc", "_Address", b"_Address", "_BinaryLoc", b"_BinaryLoc"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["Address", b"Address", "BinaryLoc", b"BinaryLoc", "GitSha", b"GitSha", "PluginCommands", b"PluginCommands", "PluginName", b"PluginName", "PluginUUID", b"PluginUUID", "_Address", b"_Address", "_BinaryLoc", b"_BinaryLoc"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_Address", b"_Address"]) -> typing.Literal["Address"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_BinaryLoc", b"_BinaryLoc"]) -> typing.Literal["BinaryLoc"] | None: ...

global___PluginDefintion = PluginDefintion

@typing.final
class Manifest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class PluginsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___PluginDefintion: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___PluginDefintion | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    PLUGINS_FIELD_NUMBER: builtins.int
    @property
    def Plugins(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___PluginDefintion]: ...
    def __init__(
        self,
        *,
        Plugins: collections.abc.Mapping[builtins.str, global___PluginDefintion] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Plugins", b"Plugins"]) -> None: ...

global___Manifest = Manifest

@typing.final
class PluginGetRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PLUGINNAME_FIELD_NUMBER: builtins.int
    PluginName: builtins.str
    def __init__(
        self,
        *,
        PluginName: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["PluginName", b"PluginName"]) -> None: ...

global___PluginGetRequest = PluginGetRequest

@typing.final
class PluginGetResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PLUGINDEF_FIELD_NUMBER: builtins.int
    @property
    def PluginDef(self) -> global___PluginDefintion: ...
    def __init__(
        self,
        *,
        PluginDef: global___PluginDefintion | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["PluginDef", b"PluginDef"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["PluginDef", b"PluginDef"]) -> None: ...

global___PluginGetResponse = PluginGetResponse

@typing.final
class PluginListResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PLUGINNAMES_FIELD_NUMBER: builtins.int
    @property
    def PluginNames(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        PluginNames: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["PluginNames", b"PluginNames"]) -> None: ...

global___PluginListResponse = PluginListResponse

@typing.final
class PluginRegisterRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PLUGINSERVICEDEFINITION_FIELD_NUMBER: builtins.int
    @property
    def PluginServiceDefinition(self) -> global___PluginDefintion: ...
    def __init__(
        self,
        *,
        PluginServiceDefinition: global___PluginDefintion | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["PluginServiceDefinition", b"PluginServiceDefinition"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["PluginServiceDefinition", b"PluginServiceDefinition"]) -> None: ...

global___PluginRegisterRequest = PluginRegisterRequest

@typing.final
class PluginRegisterResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REPONSECODE_FIELD_NUMBER: builtins.int
    PLUGINASSIGNEDUUID_FIELD_NUMBER: builtins.int
    REPONSESTRING_FIELD_NUMBER: builtins.int
    ReponseCode: builtins.int
    PluginAssignedUUID: builtins.int
    ReponseString: builtins.str
    def __init__(
        self,
        *,
        ReponseCode: builtins.int = ...,
        PluginAssignedUUID: builtins.int = ...,
        ReponseString: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["PluginAssignedUUID", b"PluginAssignedUUID", "ReponseCode", b"ReponseCode", "ReponseString", b"ReponseString"]) -> None: ...

global___PluginRegisterResponse = PluginRegisterResponse

@typing.final
class PluginUnaryRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLIENTCOMMANDFILE_FIELD_NUMBER: builtins.int
    ClientCommandFile: builtins.bytes
    def __init__(
        self,
        *,
        ClientCommandFile: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ClientCommandFile", b"ClientCommandFile"]) -> None: ...

global___PluginUnaryRequest = PluginUnaryRequest

@typing.final
class PluginUnaryResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERVERRESPONSEFILE_FIELD_NUMBER: builtins.int
    ServerResponseFile: builtins.bytes
    def __init__(
        self,
        *,
        ServerResponseFile: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ServerResponseFile", b"ServerResponseFile"]) -> None: ...

global___PluginUnaryResponse = PluginUnaryResponse
